# Generated by Django 4.1 on 2022-08-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0002_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("time_minutes", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("ingredients", models.ManyToManyField(to="recipe.ingredient")),
                ("tags", models.ManyToManyField(to="recipe.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
