# Generated by Django 4.1 on 2022-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
